version: '3'

services:
  ctf-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lfi_2-reto
    ports:
      - "8082:80"   # Puerto para el servidor web
      - "2222:22"   # Puerto para SSH
    restart: unless-stopped
    volumes:
      - ctf_data:/var/www/html/uploads  # Persistencia para los archivos subidos

volumes:
  ctf_data:    # Volumen para mantener los archivos subidos entre reinicios
